In [2]:
import os 
import pandas as pd
os.chdir("/scratch/dr2de/cif/")

In [3]:
df1 = pd.read_csv("cif-2018-12-10.csv", index_col=False, parse_dates=["reporttime"])

In [6]:
df1.head(20)

,tlp,group,reporttime,indicator,firsttime,lasttime,count,tags,description,confidence,rdata,provider
0,green,everyone,2018-12-10 20:57:05.276128,222.128.92.250,2018-12-10T20:57:05.276109Z,2018-12-10T20:57:05.276109Z,1,honeypot,NaN,8.0,NaN,uwaterloo-chn
1,green,everyone,2018-12-10 20:57:50.419807,91.222.61.252,2018-11-08T19:27:52.741958Z,2018-12-10T20:57:50.419407Z,11,honeypot,NaN,8.0,NaN,uwaterloo-chn
2,green,everyone,2018-12-10 20:57:56.253922,112.231.232.98,2018-12-10T20:57:56.253904Z,2018-12-10T20:57:56.253904Z,1,honeypot,NaN,8.0,NaN,uwaterloo-chn
3,green,everyone,2018-12-10 20:58:41.725163,212.115.239.85,2018-12-10T20:58:41.725147Z,2018-12-10T20:58:41.725147Z,1,honeypot,NaN,8.0,NaN,uwaterloo-chn
4,green,everyone,2018-12-10 20:59:12.338698,203.198.158.147,2018-11-18T13:29:14.639896Z,2018-12-10T20:59:12.338322Z,44,honeypot,NaN,8.0,NaN,uwaterloo-chn
5,green,everyone,2018-12-10 20:59:27.881184,128.199.118.81,2018-12-07T18:30:16.587343Z,2018-12-10T20:59:27.880797Z,4,honeypot,NaN,8.0,NaN,uwaterloo-chn
6,green,everyone,2018-12-10 21:00:04.085072,79.37.135.138,2018-12-10T21:00:04.085052Z,2018-12-10T21:00:04.085052Z,1,honeypot,NaN,8.0,NaN,uwaterloo-chn
7,green,everyone,2018-12-10 21:00:24.581555,114.113.90.9,2018-12-10T21:00:24.559211Z,2018-12-10T21:00:24.581172Z,6,honeypot,NaN,8.0,NaN,uwaterloo-chn
8,green,everyone,2018-12-10 21:01:15.418779,108.163.176.162,2018-12-10T21:01:15.418761Z,2018-12-10T21:01:15.418761Z,1,honeypot,NaN,8.0,NaN,uwaterloo-chn
9,green,everyone,2018-12-10 21:04:05.176730,201.124.108.239,2018-12-10T21:01:40.739330Z,2018-12-10T21:04:05.176350Z,5,honeypot,NaN,8.0,NaN,uwaterloo-chn
10,green,everyone,2018-12-10 21:06:54.165390,104.248.32.222,2018-12-10T21:02:00.855092Z,2018-12-10T21:06:54.164960Z,30,honeypot,NaN,8.0,NaN,nccu-chn
11,green,everyone,2018-12-10 21:09:00.573668,128.199.87.48,2018-11-28T12:59:22.828190Z,2018-12-10T21:09:00.573250Z,19,honeypot,NaN,8.0,NaN,uwaterloo-chn
12,green,everyone,2018-12-10 21:09:35.666157,113.141.70.46,2018-12-10T21:09:35.659982Z,2018-12-10T21:09:35.665716Z,2,honeypot,NaN,8.0,NaN,uwaterloo-chn
13,green,everyone,2018-12-10 21:10:27.041370,200.87.31.188,2018-11-29T21:04:47.059946Z,2018-12-10T21:10:27.040968Z,4,honeypot,NaN,8.0,NaN,uwaterloo-chn
14,green,everyone,2018-12-10 21:10:32.357806,213.166.193.194,2018-12-10T21:10:32.351368Z,2018-12-10T21:10:32.357406Z,2,honeypot,NaN,8.0,NaN,uwaterloo-chn
15,green,everyone,2018-12-10 21:11:13.239801,82.127.220.180,2018-12-02T01:13:37.569277Z,2018-12-10T21:11:13.239374Z,12,honeypot,NaN,8.0,NaN,nccu-chn
16,green,everyone,2018-12-10 21:11:40.377105,209.141.43.189,2018-12-05T21:07:31.188067Z,2018-12-10T21:11:40.376739Z,30,honeypot,NaN,8.0,NaN,nccu-chn
17,green,everyone,2018-12-10 21:12:31.105031,46.138.8.102,2018-12-10T21:12:31.098956Z,2018-12-10T21:12:31.104657Z,2,honeypot,NaN,8.0,NaN,uwaterloo-chn
18,green,everyone,2018-12-10 21:13:16.716677,210.9.148.206,2018-11-21T16:11:17.081310Z,2018-12-10T21:13:16.716307Z,141,honeypot,NaN,8.0,NaN,uwaterloo-chn
19,green,everyone,2018-12-10 21:14:43.329828,198.23.175.70,2018-12-10T21:14:32.841334Z,2018-12-10T21:14:43.329417Z,2,honeypot,NaN,8.0,NaN,uwaterloo-chn

In [8]:
os.chdir("/scratch/dr2de/bro-anonymized-labeled-conn-logs/2018-12-10/")

In [60]:
# conn_log file to be read in (merged across all hours of a day)
file='merged_conn.log'
#labeled=[]

# name of file to be written
outFile='labeled_merged_conn.log'
out=open(outFile, 'w')
f=open(file,'r')
line=f.readline().strip()

counter=0
ip_set=set(df1.indicator.tolist())

while line:
    
    # ignore lines begining with '#'
    if '#' in line: 
        line=f.readline().strip()
        continue
        
    
    temp=line.split('\t')
    
    if temp[2] in ip_set:
        out.write(line+'\t'+'1'+'\n')
        #labeled.append(1)
    else:
        out.write(line+'\t'+'0'+'\n')
        #labeled.append(0)
    
    
    line=f.readline().strip()
    
f.close()
out.close()

In [54]:
# number of times malicious IP in cif and conn logs 
sum(labeled)

18218992

In [ ]:
df['label']=labeled